In [1]:
!pip install transformers

Collecting transformers
  Downloading transformers-5.10.1-py3-none-any.whl.metadata (33 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.17.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from transformers) (2026.5.9)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Collecting typer (from transformers)
  Downloading typer-0.26.7-py3-none-any.whl.metadata (16 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from transformers) (4.67.3)
Requirement already satisfied: click>=8.4.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.1)
Requirement already satisfied: filelock>=3.10.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Collecting typer (from transformers)
  Downloading typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: rich>=13.8.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from typer->transformers) (15.0.0)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: colorama in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from click>=8.4.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from rich>=13.8.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from rich>=13.8.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\pgcp-ai\.conda\envs\dl_env\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
Downloading transformers-5.10.1-py3-none-any.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.0 MB 6.7 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.0 MB 4.6 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/11.0 MB 4.6 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/11.0 MB 4.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/11.0 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/11.0 MB 1.2 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/11.0 MB 1.2 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/11.0 MB 847.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.0 MB 847.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.0 MB 847.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.0 MB 847.3 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/11.0 MB 847.3 kB/s eta 0:00:12
   ------ --------------------------------- 1.8/11.0 MB 599.2 kB/s eta 0:00:16
   ------ --------------------------------- 1.8/11.0 MB 599.2 kB/s eta 0:00:16
   ------- -------------------------------- 2.1/11.0 MB 605.4 kB/s eta 0:00:15
   ------- -------------------------------- 2.1/11.0 MB 605.4 kB/s eta 0:00:15
   -------- ------------------------------- 2.4/11.0 MB 599.2 kB/s eta 0:00:15
   --------- ------------------------------ 2.6/11.0 MB 642.5 kB/s eta 0:00:14
   --------- ------------------------------ 2.6/11.0 MB 642.5 kB/s eta 0:00:14
   --------- ------------------------------ 2.6/11.0 MB 642.5 kB/s eta 0:00:14
   ---------- ----------------------------- 2.9/11.0 MB 601.2 kB/s eta 0:00:14
   ---------- ----------------------------- 2.9/11.0 MB 601.2 kB/s eta 0:00:14
   ----------- ---------------------------- 3.1/11.0 MB 597.3 kB/s eta 0:00:14
   ----------- ---------------------------- 3.1/11.0 MB 597.3 kB/s eta 0:00:14
   ------------ --------------------------- 3.4/11.0 MB 586.9 kB/s eta 0:00:13
   ------------ --------------------------- 3.4/11.0 MB 586.9 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.0 MB 592.7 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.0 MB 592.7 kB/s eta 0:00:13
   ------------- -------------------------- 3.7/11.0 MB 592.7 kB/s eta 0:00:13
   -------------- ------------------------- 3.9/11.0 MB 581.3 kB/s eta 0:00:13
   -------------- ------------------------- 3.9/11.0 MB 581.3 kB/s eta 0:00:13
   --------------- ------------------------ 4.2/11.0 MB 587.9 kB/s eta 0:00:12
   ---------------- ----------------------- 4.5/11.0 MB 597.8 kB/s eta 0:00:11
   ---------------- ----------------------- 4.5/11.0 MB 597.8 kB/s eta 0:00:11
   ---------------- ----------------------- 4.5/11.0 MB 597.8 kB/s eta 0:00:11
   ---------------- ----------------------- 4.5/11.0 MB 597.8 kB/s eta 0:00:11
   ---------------- ----------------------- 4.5/11.0 MB 597.8 kB/s eta 0:00:11
   ----------------- ---------------------- 4.7/11.0 MB 549.5 kB/s eta 0:00:12
   ----------------- ---------------------- 4.7/11.0 MB 549.5 kB/s eta 0:00:12
   ----------------- ---------------------- 4.7/11.0 MB 549.5 kB/s eta 0:00:12
   ----------------- ---------------------- 4.7/11.0 MB 549.5 kB/s eta 0:00:12
   ------------------ --------------------- 5.0/11.0 MB 528.9 kB/s eta 0:00:12
   ------------------ --------------------- 5.0/11.0 MB 528.9 kB/s eta 0:00:12
   ------------------ --------------------- 5.0/11.0 MB 528.9 kB/s eta 0:00:12
   ------------------ --------------------- 5.0/11.0 MB 528.9 kB/s eta 0:00:12
   ------------------- -------------------- 5.2/11.0 MB 503.6 kB/s eta 0:00:12
   ------------------- -------------------- 5.2/11.0 MB 503.6 kB/s eta 0:00:12
   -------------------- ------------------- 5.5/11.0 MB 510.7 kB/s eta 0:00:11
   -------------------- ------------------- 5.8/11.0 MB 525.0 kB/s eta 0:00:10
   --------------------- ------------------ 6.0/11.0 MB 542.0 kB/s eta 0:00:10
   --------------------- ------------------ 6.0/11.0 MB 542.0 kB/s eta 0:00:10
   ---------------------- ----------------- 6.3/11.0 MB 539.7 kB/s eta 0:00:09
   ---------------------- ----------------- 6.3/11.0 MB 539.7 kB/s eta 0:00:09
   ----------------------- ---------------- 6.6/11.0 MB 541.2 kB/s eta 0:00:09
   ----------------------- ---------------- 6.6/11.0 MB 541.2 kB/s eta 0:00:09
   ----------------------- ---------------- 6.6/11.0 MB 541.2 kB/s eta 0:00:09
   ------------------------ --------------- 6.8/11.0 MB 539.8 kB/s eta 0:00:08
   ------------------------- -------------- 7.1/11.0 MB 547.3 kB/s eta 0:00:08
   ------------------------- -------------- 7.1/11.0 MB 547.3 kB/s eta 0:00:08
   ------------------------- -------------- 7.1/11.0 MB 547.3 kB/s eta 0:00:08
   ------------------------- -------------- 7.1/11.0 MB 547.3 kB/s eta 0:00:08
   -------------------------- ------------- 7.3/11.0 MB 532.9 kB/s eta 0:00:07
   -------------------------- ------------- 7.3/11.0 MB 532.9 kB/s eta 0:00:07
   --------------------------- ------------ 7.6/11.0 MB 536.2 kB/s eta 0:00:07
   --------------------------- ------------ 7.6/11.0 MB 536.2 kB/s eta 0:00:07
   --------------------------- ------------ 7.6/11.0 MB 536.2 kB/s eta 0:00:07
   --------------------------- ------------ 7.6/11.0 MB 536.2 kB/s eta 0:00:07
   ---------------------------- ----------- 7.9/11.0 MB 523.2 kB/s eta 0:00:07
   ---------------------------- ----------- 7.9/11.0 MB 523.2 kB/s eta 0:00:07
   ----------------------------- ---------- 8.1/11.0 MB 524.3 kB/s eta 0:00:06
   ----------------------------- ---------- 8.1/11.0 MB 524.3 kB/s eta 0:00:06
   ----------------------------- ---------- 8.1/11.0 MB 524.3 kB/s eta 0:00:06
   ----------------------------- ---------- 8.1/11.0 MB 524.3 kB/s eta 0:00:06
   ----------------------------- ---------- 8.1/11.0 MB 524.3 kB/s eta 0:00:06
   ------------------------------ --------- 8.4/11.0 MB 505.4 kB/s eta 0:00:06
   ------------------------------ --------- 8.4/11.0 MB 505.4 kB/s eta 0:00:06
   ------------------------------ --------- 8.4/11.0 MB 505.4 kB/s eta 0:00:06
   ------------------------------- -------- 8.7/11.0 MB 500.8 kB/s eta 0:00:05
   ------------------------------- -------- 8.7/11.0 MB 500.8 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   -------------------------------- ------- 8.9/11.0 MB 501.5 kB/s eta 0:00:05
   --------------------------------- ------ 9.2/11.0 MB 458.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.2/11.0 MB 458.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.2/11.0 MB 458.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.2/11.0 MB 458.9 kB/s eta 0:00:04
   --------------------------------- ------ 9.2/11.0 MB 458.9 kB/s eta 0:00:04
   ---------------------------------- ----- 9.4/11.0 MB 445.9 kB/s eta 0:00:04
   ---------------------------------- ----- 9.4/11.0 MB 445.9 kB/s eta 0:00:04
   ----------------------------------- ---- 9.7/11.0 MB 452.4 kB/s eta 0:00:03
   ----------------------------------- ---- 9.7/11.0 MB 452.4 kB/s eta 0:00:03
   ------------------------------------ --- 10.0/11.0 MB 452.8 kB/s eta 0:00:03
   ------------------------------------ --- 10.0/11.0 MB 452.8 kB/s eta 0:00:03
   ------------------------------------ --- 10.0/11.0 MB 452.8 kB/s eta 0:00:03
   ------------------------------------ --- 10.0/11.0 MB 452.8 kB/s eta 0:00:03
   ------------------------------------ --- 10.0/11.0 MB 452.8 kB/s eta 0:00:03
   ------------------------------------- -- 10.2/11.0 MB 444.9 kB/s eta 0:00:02
   ------------------------------------- -- 10.2/11.0 MB 444.9 kB/s eta 0:00:02
   -------------------------------------- - 10.5/11.0 MB 446.9 kB/s eta 0:00:02
   ---------------------------------------  10.7/11.0 MB 453.1 kB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 453.1 kB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 457.1 kB/s  0:00:23
Downloading huggingface_hub-1.17.0-py3-none-any.whl (671 kB)
   ---------------------------------------- 0.0/671.5 kB ? eta -:--:--
   ---------------------------------------- 0.0/671.5 kB ? eta -:--:--
   --------------- ------------------------ 262.1/671.5 kB ? eta -:--:--
   --------------- ------------------------ 262.1/671.5 kB ? eta -:--:--
   --------------- ------------------------ 262.1/671.5 kB ? eta -:--:--
   ----------------------------- -------- 524.3/671.5 kB 524.3 kB/s eta 0:00:01
   ---------------------------------------- 671.5/671.5 kB 513.7 kB/s  0:00:01
Downloading hf_xet-1.5.0-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 372.9 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 372.9 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 372.9 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 372.9 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 372.9 kB/s eta 0:00:10
   ----- ---------------------------------- 0.5/4.0 MB 372.9 kB/s eta 0:00:10
   ------- -------------------------------- 0.8/4.0 MB 256.1 kB/s eta 0:00:13
   ------- -------------------------------- 0.8/4.0 MB 256.1 kB/s eta 0:00:13
   ---------- ----------------------------- 1.0/4.0 MB 308.8 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/4.0 MB 308.8 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/4.0 MB 308.8 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/4.0 MB 308.8 kB/s eta 0:00:10
   ---------- ----------------------------- 1.0/4.0 MB 308.8 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/4.0 MB 291.8 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/4.0 MB 291.8 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/4.0 MB 291.8 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/4.0 MB 291.8 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/4.0 MB 291.8 kB/s eta 0:00:10
   ------------- -------------------------- 1.3/4.0 MB 291.8 kB/s eta 0:00:10
   --------------- ------------------------ 1.6/4.0 MB 266.3 kB/s eta 0:00:10
   ------------------ --------------------- 1.8/4.0 MB 306.9 kB/s eta 0:00:07
   ------------------ --------------------- 1.8/4.0 MB 306.9 kB/s eta 0:00:07
   ------------------ --------------------- 1.8/4.0 MB 306.9 kB/s eta 0:00:07
   ------------------ --------------------- 1.8/4.0 MB 306.9 kB/s eta 0:00:07
   ------------------ --------------------- 1.8/4.0 MB 306.9 kB/s eta 0:00:07
   ------------------ --------------------- 1.8/4.0 MB 306.9 kB/s eta 0:00:07
   --------------------- ------------------ 2.1/4.0 MB 287.8 kB/s eta 0:00:07
   --------------------- ------------------ 2.1/4.0 MB 287.8 kB/s eta 0:00:07
   ----------------------- ---------------- 2.4/4.0 MB 310.7 kB/s eta 0:00:06
   ----------------------- ---------------- 2.4/4.0 MB 310.7 kB/s eta 0:00:06
   -------------------------- ------------- 2.6/4.0 MB 328.2 kB/s eta 0:00:05
   -------------------------- ------------- 2.6/4.0 MB 328.2 kB/s eta 0:00:05
   ----------------------------- ---------- 2.9/4.0 MB 343.1 kB/s eta 0:00:04
   ----------------------------- ---------- 2.9/4.0 MB 343.1 kB/s eta 0:00:04
   ------------------------------- -------- 3.1/4.0 MB 358.3 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 358.3 kB/s eta 0:00:03
   ------------------------------- -------- 3.1/4.0 MB 358.3 kB/s eta 0:00:03
   ---------------------------------- ----- 3.4/4.0 MB 360.1 kB/s eta 0:00:02
   ---------------------------------- ----- 3.4/4.0 MB 360.1 kB/s eta 0:00:02
   ---------------------------------- ----- 3.4/4.0 MB 360.1 kB/s eta 0:00:02
   ---------------------------------- ----- 3.4/4.0 MB 360.1 kB/s eta 0:00:02
   ------------------------------------ --- 3.7/4.0 MB 355.8 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 355.8 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 355.8 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 355.8 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 352.7 kB/s  0:00:11
Using cached tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
Downloading typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached safetensors-0.7.0-cp38-abi3-win_amd64.whl (341 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: shellingham, safetensors, hf-xet, annotated-doc, typer, huggingface-hub, tokenizers, transformers

   ---------------------------------------- 0/8 [shellingham]
   ----- ---------------------------------- 1/8 [safetensors]
   ----- ---------------------------------- 1/8 [safetensors]
   --------------- ------------------------ 3/8 [annotated-doc]
   -------------------- ------------------- 4/8 [typer]
   -------------------- ------------------- 4/8 [typer]
   -------------------- ------------------- 4/8 [typer]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]
   ------------------------- -------------- 5/8 [huggingface-hub]

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

### Text Classification

In [2]:
from transformers import pipeline

pipe = pipeline("text-generation", model="distilbert/distilgpt2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

c:\Users\PGCP-AI\.conda\envs\dl_env\lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\PGCP-AI\.cache\huggingface\hub\models--distilbert--distilgpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/353M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [4]:
classifier=pipeline('text-classification')

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

c:\Users\PGCP-AI\.conda\envs\dl_env\lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\PGCP-AI\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [5]:
import pandas as pd
text = 'It was possible for him.so he did it.'
result=classifier(text)

In [6]:
df=pd.DataFrame(result)
df

      label     score
0  POSITIVE  0.974791

In [8]:
text = 'Nothing is impossible without these efforts!'
results = classifier(text)
df = pd.DataFrame(results)
df

      label     score
0  POSITIVE  0.996524